DROP TABLE IF EXISTS system_alerts CASCADE;
DROP TABLE IF EXISTS satellite_imagery CASCADE;
DROP TABLE IF EXISTS cctv_alerts CASCADE;
DROP TABLE IF EXISTS sensor_readings CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS lgus CASCADE;
